<a href="https://colab.research.google.com/github/vishaljoshi24/DungeonsAndDragonsTurnClassification/blob/main/data_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DATA

In [1]:
from datasets import load_dataset
import pandas as pd

In [2]:
df = pd.read_json("hf://datasets/garrykuwanto/crd3_training_pairs/crd3_training_pairs_no_llm.json")

In [3]:
df

,query,passage
0,Dialogue context: MATT: And welcome to tonight...,ZAC: Testicular.
1,Dialogue context: ZAC: Fantastical? MATT: Fant...,MATT: It is. It is a testicle episode of Criti...
2,Dialogue context: MATT: Fantastical. ZAC: Test...,ZAC: Cue cut to Ashley!
3,Dialogue context: ZAC: Testicular. MATT: It is...,MATT: Yay! Hi Ashley! She's dancing for it. So...
4,Dialogue context: MATT: It is. It is a testicl...,ZAC: We've got a couple of quick announcements...
...,...,...
2360577,Player says: Not continuing the song... (all l...,"DM responds: Guys, thank you so much for watch..."
2360578,Player says: Not Taliesin.,"DM responds: Not Taliesin, sorry. Liam, Marish..."
2360579,Player says: Saturday.,DM responds: Sorry. Saturday. Friday. It's -
2360580,Player says: It technically is tomorrow.,"DM responds: No, it's not tomorrow yet. Sorry...."
2360581,Player says: Starts tomorrow at 7pm!,DM responds: Thank you. Tomorrow at 7pm. It go...

In [4]:
query = []
passage = []
for i in range(len(df[0:])):
  query.append(df['query'][i])
  passage.append(df['passage'][i])

df1 = pd.DataFrame({'context': query, 'current turn': passage})

In [5]:
df1

,context,current turn
0,Dialogue context: MATT: And welcome to tonight...,ZAC: Testicular.
1,Dialogue context: ZAC: Fantastical? MATT: Fant...,MATT: It is. It is a testicle episode of Criti...
2,Dialogue context: MATT: Fantastical. ZAC: Test...,ZAC: Cue cut to Ashley!
3,Dialogue context: ZAC: Testicular. MATT: It is...,MATT: Yay! Hi Ashley! She's dancing for it. So...
4,Dialogue context: MATT: It is. It is a testicl...,ZAC: We've got a couple of quick announcements...
...,...,...
2360577,Player says: Not continuing the song... (all l...,"DM responds: Guys, thank you so much for watch..."
2360578,Player says: Not Taliesin.,"DM responds: Not Taliesin, sorry. Liam, Marish..."
2360579,Player says: Saturday.,DM responds: Sorry. Saturday. Friday. It's -
2360580,Player says: It technically is tomorrow.,"DM responds: No, it's not tomorrow yet. Sorry...."
2360581,Player says: Starts tomorrow at 7pm!,DM responds: Thank you. Tomorrow at 7pm. It go...

In [6]:
df2 = df1[(~df1['context'].str.startswith('Scene context:')) & (~df1['context'].str.startswith('Player says:'))]
# (~df1['current turn'].str.startswith('MATT:'))
# (~df1['current turn'].str.startswith('DM Responds:'))
# (~df1['current turn'].str.startswith('MATT Responds:')) &

In [7]:
df2

,context,current turn
0,Dialogue context: MATT: And welcome to tonight...,ZAC: Testicular.
1,Dialogue context: ZAC: Fantastical? MATT: Fant...,MATT: It is. It is a testicle episode of Criti...
2,Dialogue context: MATT: Fantastical. ZAC: Test...,ZAC: Cue cut to Ashley!
3,Dialogue context: ZAC: Testicular. MATT: It is...,MATT: Yay! Hi Ashley! She's dancing for it. So...
4,Dialogue context: MATT: It is. It is a testicl...,ZAC: We've got a couple of quick announcements...
...,...,...
2356317,ALL says: Saturday.,MATT responds: Sorry. Saturday. Friday. It's -
2356318,MATT says: Sorry. Saturday. Friday. It's -,TALIESIN responds: It technically is tomorrow.
2356319,TALIESIN says: It technically is tomorrow.,"MATT responds: No, it's not tomorrow yet. Sorr..."
2356320,"MATT says: No, it's not tomorrow yet. Sorry. S...",LUCAS responds: Starts tomorrow at 7pm!
2356321,LUCAS says: Starts tomorrow at 7pm!,MATT responds: Thank you. Tomorrow at 7pm. It ...

In [8]:
df3 = df2[(~df2['current turn'].str.startswith('AUDIENCE:'))]

In [9]:
df3

,context,current turn
0,Dialogue context: MATT: And welcome to tonight...,ZAC: Testicular.
1,Dialogue context: ZAC: Fantastical? MATT: Fant...,MATT: It is. It is a testicle episode of Criti...
2,Dialogue context: MATT: Fantastical. ZAC: Test...,ZAC: Cue cut to Ashley!
3,Dialogue context: ZAC: Testicular. MATT: It is...,MATT: Yay! Hi Ashley! She's dancing for it. So...
4,Dialogue context: MATT: It is. It is a testicl...,ZAC: We've got a couple of quick announcements...
...,...,...
2356317,ALL says: Saturday.,MATT responds: Sorry. Saturday. Friday. It's -
2356318,MATT says: Sorry. Saturday. Friday. It's -,TALIESIN responds: It technically is tomorrow.
2356319,TALIESIN says: It technically is tomorrow.,"MATT responds: No, it's not tomorrow yet. Sorr..."
2356320,"MATT says: No, it's not tomorrow yet. Sorry. S...",LUCAS responds: Starts tomorrow at 7pm!
2356321,LUCAS says: Starts tomorrow at 7pm!,MATT responds: Thank you. Tomorrow at 7pm. It ...

In [10]:
df4 = df3.drop_duplicates(subset=['context'], inplace=False)

In [11]:
df4

,context,current turn
0,Dialogue context: MATT: And welcome to tonight...,ZAC: Testicular.
1,Dialogue context: ZAC: Fantastical? MATT: Fant...,MATT: It is. It is a testicle episode of Criti...
2,Dialogue context: MATT: Fantastical. ZAC: Test...,ZAC: Cue cut to Ashley!
3,Dialogue context: ZAC: Testicular. MATT: It is...,MATT: Yay! Hi Ashley! She's dancing for it. So...
4,Dialogue context: MATT: It is. It is a testicl...,ZAC: We've got a couple of quick announcements...
...,...,...
2344063,"Dialogue context: LIAM: Ja, but I rolled an 18...",SAM: I'll just run over to Jester and give her...
2344065,Dialogue context: SAM: I'll just run over to J...,MARISHA: They're all unconscious?
2344068,Dialogue context: MARISHA: They're all unconsc...,KHARY: It will be. It's absolutely better than...
2352766,Dialogue context: TRAVIS: Who's with the burnt...,LAURA: Big tavern brawl!
2353049,Dialogue context: in unison MARISHA TALIESIN: ...,MATT: Sorry. Saturday. Friday. It's -

In [12]:
df5 = df4.drop_duplicates(subset=['current turn'], inplace=False)

In [13]:
df5

,context,current turn
0,Dialogue context: MATT: And welcome to tonight...,ZAC: Testicular.
1,Dialogue context: ZAC: Fantastical? MATT: Fant...,MATT: It is. It is a testicle episode of Criti...
2,Dialogue context: MATT: Fantastical. ZAC: Test...,ZAC: Cue cut to Ashley!
3,Dialogue context: ZAC: Testicular. MATT: It is...,MATT: Yay! Hi Ashley! She's dancing for it. So...
4,Dialogue context: MATT: It is. It is a testicl...,ZAC: We've got a couple of quick announcements...
...,...,...
2259502,MATT says: Gathering up the rest of those who ...,ASHLEY responds: Sex. It's sex. It's lots of s...
2259503,ASHLEY says: Sex. It's sex. It's lots of sex. ...,"MATT responds: All right. Well then, we're goi..."
2259504,"MATT says: All right. Well then, we're going t...","KHARY responds: You know what, hold on! Take a..."
2259505,"KHARY says: You know what, hold on! Take a bow...",MATT responds: Thank you all so very much for ...
2329854,"Dialogue context: MATT: Hello everyone, welcom...",MATT: That I get to open.

In [14]:
df6 = df5[70:] #Point at which gameplay starts

In [15]:
df6

,context,current turn
71,Dialogue context: ASHLEY: Yeah! MATT: By the w...,ASHLEY: I know! I didn't even mean-- I just pu...
72,"Dialogue context: MATT: By the way, thank you ...","TRAVIS: Mass panic, it's no big deal."
73,Dialogue context: in unison SAM MATT: Includin...,MATT: You're technically still here. And you k...
74,Dialogue context: ASHLEY: I know! I didn't eve...,ASHLEY: Really? (laughs)
75,"Dialogue context: TRAVIS: Mass panic, it's no ...","TRAVIS: Hello, Pike!"
...,...,...
2259502,MATT says: Gathering up the rest of those who ...,ASHLEY responds: Sex. It's sex. It's lots of s...
2259503,ASHLEY says: Sex. It's sex. It's lots of sex. ...,"MATT responds: All right. Well then, we're goi..."
2259504,"MATT says: All right. Well then, we're going t...","KHARY responds: You know what, hold on! Take a..."
2259505,"KHARY says: You know what, hold on! Take a bow...",MATT responds: Thank you all so very much for ...
2329854,"Dialogue context: MATT: Hello everyone, welcom...",MATT: That I get to open.

In [16]:
df6.to_json('cleaned_data.json', orient='split', compression='infer', index=True)

In [17]:
cleaned_data = pd.read_json('cleaned_data.json', orient='split', compression='infer')

In [18]:
cleaned_data

,context,current turn
71,Dialogue context: ASHLEY: Yeah! MATT: By the w...,ASHLEY: I know! I didn't even mean-- I just pu...
72,"Dialogue context: MATT: By the way, thank you ...","TRAVIS: Mass panic, it's no big deal."
73,Dialogue context: in unison SAM MATT: Includin...,MATT: You're technically still here. And you k...
74,Dialogue context: ASHLEY: I know! I didn't eve...,ASHLEY: Really? (laughs)
75,"Dialogue context: TRAVIS: Mass panic, it's no ...","TRAVIS: Hello, Pike!"
...,...,...
2259502,MATT says: Gathering up the rest of those who ...,ASHLEY responds: Sex. It's sex. It's lots of s...
2259503,ASHLEY says: Sex. It's sex. It's lots of sex. ...,"MATT responds: All right. Well then, we're goi..."
2259504,"MATT says: All right. Well then, we're going t...","KHARY responds: You know what, hold on! Take a..."
2259505,"KHARY says: You know what, hold on! Take a bow...",MATT responds: Thank you all so very much for ...
2329854,"Dialogue context: MATT: Hello everyone, welcom...",MATT: That I get to open.

In [19]:
# unlabelled_trainset_draft = df1[113:513]

# filename = 'unlabelled_trainset_draft.xlsx'
# unlabelled_trainset_draft.to_excel(filename)

In [20]:
cleaned_data[284:]

,context,current turn
382,"Dialogue context: LAURA: Except for you, darli...",MATT: Yeah. This giant rotund Percy on his han...
383,Dialogue context: MATT: It's very weird. You'r...,LAURA: That is awkward.
384,Dialogue context: TALIESIN: Bear-Percy is espe...,"MATT: It's a very strange visual, and you're v..."
385,Dialogue context: MATT: Yeah. This giant rotun...,ASHLEY: I give Percy-Trink some ear scratches.
386,Dialogue context: LAURA: That is awkward. MATT...,LAURA: He likes it.
...,...,...
2259502,MATT says: Gathering up the rest of those who ...,ASHLEY responds: Sex. It's sex. It's lots of s...
2259503,ASHLEY says: Sex. It's sex. It's lots of sex. ...,"MATT responds: All right. Well then, we're goi..."
2259504,"MATT says: All right. Well then, we're going t...","KHARY responds: You know what, hold on! Take a..."
2259505,"KHARY says: You know what, hold on! Take a bow...",MATT responds: Thank you all so very much for ...
2329854,"Dialogue context: MATT: Hello everyone, welcom...",MATT: That I get to open.

In [21]:
cleaned_data[13300:13700]

,context,current turn
23688,Dialogue context: SAM: I don't think it's loud...,"SAM: Oh no - well, it's a wave of thunderous f..."
23689,Dialogue context: LIAM: We're total fake geeks...,MATT: I would say thunderous force isn't a thu...
23690,Dialogue context: TALIESIN: Such fake geeks. S...,"SAM: Okay, fine."
23691,"Dialogue context: SAM: Oh no - well, it's a wa...",MATT: So keep that in mind.
23692,Dialogue context: MATT: I would say thunderous...,"LAURA: Keyleth, fly up and cast Pass Without T..."
...,...,...
24123,Dialogue context: LIAM: It's so handsome. MARI...,MARISHA: Oh. We don't know yet.
24124,Dialogue context: MARISHA: Who is it going to?...,"MATT: Whenever that happens, that will be goin..."
24125,Dialogue context: MATT: Some lucky person in t...,"SAM: Also, we've got these t-shirts. You shoul..."
24126,Dialogue context: MARISHA: Oh. We don't know y...,MATT: We're going to now look into--
24127,"Dialogue context: MATT: Whenever that happens,...","MARISHA: Yes, let us know if you want them."

In [45]:
test_set = cleaned_data[18000:18100]
optimisation_set = cleaned_data[14200:14600]
val_set = cleaned_data[14000:14100]

In [46]:
optimisation_set

,context,current turn
24698,Dialogue context: MATT: All right. Vex? MARISH...,"LAURA: Oh, well, let's make this nice and easy..."
24700,Dialogue context: MARISHA: Just gnawing on the...,TRAVIS: (eager snarling)
24701,"Dialogue context: LAURA: Oh, well, let's make ...","MATT: All right, Grog, it's your turn."
24702,"Dialogue context: LAURA: Oh, well, let's make ...",TRAVIS: (eager snarling continues)
24703,Dialogue context: TRAVIS: (eager snarling) MAT...,MARISHA: Does he get advantage because we're a...
...,...,...
25129,Dialogue context: TRAVIS: Yeah! (all laugh) MA...,ORION: That's a good idea. Grog! You can go hu...
25130,"Dialogue context: MATT: Oh, Grog. LAURA: That ...",LIAM: She can hump your leg.
25131,Dialogue context: LAURA: That would be the mos...,TRAVIS: Did you see her work in that room of b...
25132,Dialogue context: ORION: That's a good idea. G...,TALIESIN: Only one of them is demanding that I...
25133,Dialogue context: LIAM: She can hump your leg....,MARISHA: Isn't Kima a dwarf?

In [48]:
test_set

,context,current turn
32336,Dialogue context: TRAVIS: So should we fly up ...,MARISHA: And we still have Pass Without a Trac...
32337,Dialogue context: TALIESIN: I think it'd be sa...,"LAURA: Yes, we do. She cast it."
32338,Dialogue context: TRAVIS: Let's do it. MARISHA...,"MATT: All right, now that this brief combat ha..."
32339,Dialogue context: MARISHA: And we still have P...,"LAURA: You're like, ""Gladly!"""
32341,"Dialogue context: MATT: All right, now that th...",LAURA: What about Pike? Because she just knelt...
...,...,...
32434,Dialogue context: TALIESIN: We all have to be ...,"LIAM: Yeah, that's right."
32435,Dialogue context: TRAVIS: And he can fly. SAM:...,SAM: We have too many people for the carpet an...
32436,"Dialogue context: SAM: No, he can't. He's done...",LIAM: My wings are gone. There's no wings for ...
32437,"Dialogue context: LIAM: Yeah, that's right. SA...","TRAVIS: Well, kick Trinket out of the necklace..."
32438,Dialogue context: SAM: We have too many people...,"TALIESIN: I can also climb up the wall, if nee..."

In [49]:
val_set

,context,current turn
24473,Dialogue context: ASHLEY: Can I do a Mass Cure...,"LIAM: Yes, I was about to say. I'm going to go..."
24474,Dialogue context: MATT: You can if you'd like....,TALIESIN: I'll go with him.
24475,Dialogue context: ASHLEY: Okay. I'll do that. ...,LAURA: Why don't you unlock the prison cells h...
24476,"Dialogue context: LIAM: Yes, I was about to sa...","MARISHA: Yeah, can you unlock the prison cells?"
24477,Dialogue context: TALIESIN: I'll go with him. ...,"LIAM: Oh, sorry."
...,...,...
24584,Dialogue context: MATT: 14. 10 to 5? ASHLEY: 7...,SAM: (nervously) 4.
24585,Dialogue context: ASHLEY: 7. MATT: 5 to 1? SAM...,"MATT: All right. Percy, you're up first."
24586,Dialogue context: MATT: 5 to 1? SAM: (nervousl...,TALIESIN: Where am I?
24587,Dialogue context: SAM: (nervously) 4. MATT: Al...,"MATT: You are way back in this cell, and you h..."
24588,"Dialogue context: MATT: All right. Percy, you'...",TALIESIN: I'm going to run to the hall.

In [50]:
optimisation_set

,context,current turn
24698,Dialogue context: MATT: All right. Vex? MARISH...,"LAURA: Oh, well, let's make this nice and easy..."
24700,Dialogue context: MARISHA: Just gnawing on the...,TRAVIS: (eager snarling)
24701,"Dialogue context: LAURA: Oh, well, let's make ...","MATT: All right, Grog, it's your turn."
24702,"Dialogue context: LAURA: Oh, well, let's make ...",TRAVIS: (eager snarling continues)
24703,Dialogue context: TRAVIS: (eager snarling) MAT...,MARISHA: Does he get advantage because we're a...
...,...,...
25129,Dialogue context: TRAVIS: Yeah! (all laugh) MA...,ORION: That's a good idea. Grog! You can go hu...
25130,"Dialogue context: MATT: Oh, Grog. LAURA: That ...",LIAM: She can hump your leg.
25131,Dialogue context: LAURA: That would be the mos...,TRAVIS: Did you see her work in that room of b...
25132,Dialogue context: ORION: That's a good idea. G...,TALIESIN: Only one of them is demanding that I...
25133,Dialogue context: LIAM: She can hump your leg....,MARISHA: Isn't Kima a dwarf?

In [51]:
filename_1 = 'test_set_articulation.xlsx'
filename_2 = 'optimisation_set_articulation.xlsx'
filename_3 = 'validation_set_articulation.xlsx'
test_set.to_excel(filename_1)
# optimisation_set.to_excel(filename_2)
# val_set.to_excel(filename_3)