<a href="https://colab.research.google.com/github/vishaljoshi24/DungeonsAndDragonsTurnClassification/blob/main/turn_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone 'https://github.com/vishaljoshi24/Dungeons-and-Dragons-Turn-Classification/'

Cloning into 'Dungeons-and-Dragons-Turn-Classification'...
remote: Enumerating objects: 857, done.
remote: Counting objects: 100% (343/343), done.
remote: Compressing objects: 100% (174/174), done.
remote: Total 857 (delta 273), reused 169 (delta 169), pack-reused 514 (from 1)
Receiving objects: 100% (857/857), 3.30 MiB | 13.14 MiB/s, done.
Resolving deltas: 100% (513/513), done.

In [2]:
!pip install dspy==3.2.1

Collecting dspy==3.2.1
  Downloading dspy-3.2.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: openai>=0.28.1 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1) (2.54.0)
Requirement already satisfied: regex>=2023.10.3 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1) (2025.11.3)
Requirement already satisfied: orjson>=3.9.0 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1) (3.12.0)
Requirement already satisfied: tqdm>=4.66.1 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1) (4.67.3)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1) (2.32.4)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1) (2.13.5)
Collecting litellm>=1.64.0 (from dspy==3.2.1)
  Downloading litellm-1.104.0-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 4.5 MB/s eta 0:00:00
Collecting diskcache>=5.6.0 (from dspy==3.2.1)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting json-repair>=0.54.2 (from dspy==3.2.1)
  Downloading json_repair-0.63.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1) (9.1.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1) (4.15.1)
Collecting asyncer==0.0.8 (from dspy==3.2.1)
  Downloading asyncer-0.0.8-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: cachetools>=5.5.0 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1) (6.2.6)
Requirement already satisfied: cloudpickle>=3.1.2 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1) (3.1.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1) (2.1.3)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1) (4.0.1)
Collecting gepa==0.0.27 (from gepa[dspy]==0.0.27->dspy==3.2.1)
  Downloading gepa-0.0.27-py3-none-any.whl.metadata (30 kB)
Collecting typeguard==4.4.3 (from dspy==3.2.1)
  Downloading typeguard-4.4.3-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: typing_extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from typeguard==4.4.3->dspy==3.2.1) (4.16.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio->dspy==3.2.1) (3.20)
Collecting fastuuid<1.0,>=0.14.0 (from litellm>=1.64.0->dspy==3.2.1)
  Downloading fastuuid-0.14.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.1 kB)
Collecting filelock<4.0,>=3.16.1 (from litellm>=1.64.0->dspy==3.2.1)
  Downloading filelock-3.32.7-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: httpx<1.0,>=0.28.0 in /usr/local/lib/python3.13/dist-packages (from httpx[http2]<1.0,>=0.28.0->litellm>=1.64.0->dspy==3.2.1) (0.28.1)
Requirement already satisfied: python-dotenv<2.0,>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1) (1.2.3)
Requirement already satisfied: pyyaml<7.0,>=6.0.3 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1) (6.0.3)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1) (26.3)
Collecting importlib-metadata<9.0,>=8.0.0 (from litellm>=1.64.0->dspy==3.2.1)
  Downloading importlib_metadata-8.9.0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: tiktoken<1.0,>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1) (0.14.0)
Requirement already satisfied: tokenizers<1.0,>=0.21.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1) (0.23.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.34.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1) (1.33.0)
Requirement already satisfied: click<9.0,>=8.0.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1) (8.5.0)
Requirement already satisfied: jinja2<4.0,>=3.1.6 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1) (3.1.6)
Requirement already satisfied: aiohttp<4.0,>=3.14.2 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1) (3.14.3)
Collecting pydantic-settings<3.0,>=2.14.1 (from litellm>=1.64.0->dspy==3.2.1)
  Downloading pydantic_settings-2.15.0-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: jsonschema<5.0,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1) (4.26.0)
Collecting boto3<2.0,>=1.43.1 (from litellm>=1.64.0->dspy==3.2.1)
  Downloading boto3-1.43.108-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from openai>=0.28.1->dspy==3.2.1) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.13/dist-packages (from openai>=0.28.1->dspy==3.2.1) (0.17.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.13/dist-packages (from openai>=0.28.1->dspy==3.2.1) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.0->dspy==3.2.1) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.0->dspy==3.2.1) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.0->dspy==3.2.1) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31.0->dspy==3.2.1) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31.0->dspy==3.2.1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31.0->dspy==3.2.1) (2026.7.22)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0,>=3.14.2->litellm>=1.64.0->dspy==3.2.1) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0,>=3.14.2->litellm>=1.64.0->dspy==3.2.1) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0,>=3.14.2->litellm>=1.64.0->dspy==3.2.1) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0,>=3.14.2->litellm>=1.64.0->dspy==3.2.1) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0,>=3.14.2->litellm>=1.64.0->dspy==3.2.1) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0,>=3.14.2->litellm>=1.64.0->dspy==3.2.1) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0,>=3.14.2->litellm>=1.64.0->dspy==3.2.1) (1.25.1)
Collecting botocore<1.44.0,>=1.43.108 (from boto3<2.0,>=1.43.1->litellm>=1.64.0->dspy==3.2.1)
  Downloading botocore-1.43.108-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2.0,>=1.43.1->litellm>=1.64.0->dspy==3.2.1)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.20.0,>=0.19.0 (from boto3<2.0,>=1.43.1->litellm>=1.64.0->dspy==3.2.1)
  Downloading s3transfer-0.19.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0,>=0.28.0->httpx[http2]<1.0,>=0.28.0->litellm>=1.64.0->dspy==3.2.1) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0,>=0.28.0->httpx[http2]<1.0,>=0.28.0->litellm>=1.64.0->dspy==3.2.1) (0.16.0)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.13/dist-packages (from httpx[http2]<1.0,>=0.28.0->litellm>=1.64.0->dspy==3.2.1) (4.4.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.34.0->litellm>=1.64.0->dspy==3.2.1) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.34.0->litellm>=1.64.0->dspy==3.2.1) (1.6.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.13/dist-packages (from importlib-metadata<9.0,>=8.0.0->litellm>=1.64.0->dspy==3.2.1) (4.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2<4.0,>=3.1.6->litellm>=1.64.0->dspy==3.2.1) (3.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema<5.0,>=4.0.0->litellm>=1.64.0->dspy==3.2.1) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema<5.0,>=4.0.0->litellm>=1.64.0->dspy==3.2.1) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema<5.0,>=4.0.0->litellm>=1.64.0->dspy==3.2.1) (2026.6.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.13/dist-packages (from botocore<1.44.0,>=1.43.108->boto3<2.0,>=1.43.1->litellm>=1.64.0->dspy==3.2.1) (2.9.0.post0)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.13/dist-packages (from h2<5,>=3->httpx[http2]<1.0,>=0.28.0->litellm>=1.64.0->dspy==3.2.1) (6.1.0)
Requirement already satisfied: hpack<5,>=4.2 in /usr/local/lib/python3.13/dist-packages (from h2<5,>=3->httpx[http2]<1.0,>=0.28.0->litellm>=1.64.0->dspy==3.2.1) (4.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.44.0,>=1.43.108->boto3<2.0,>=1.43.1->litellm>=1.64.0->dspy==3.2.1) (1.17.0)
Downloading dspy-3.2.1-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.0/331.0 kB 33.8 MB/s eta 0:00:00
Downloading asyncer-0.0.8-py3-none-any.whl (9.2 kB)
Downloading gepa-0.0.27-py3-none-any.whl (146 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.5/146.5 kB 17.9 MB/s eta 0:00:00
Downloading typeguard-4.4.3-py3-none-any.whl (34 kB)
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 5.3 MB/s eta 0:00:00
Downloading json_repair-0.63.5-py3-none-any.whl (51 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.3/51.3 kB 6.4 MB/s eta 0:00:00
Downloading litellm-1.104.0-cp310-abi3-manylinux_2_28_x86_64.whl (36.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.8/36.8 MB 72.8 MB/s eta 0:00:00
Downloading boto3-1.43.108-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.0/140.0 kB 16.5 MB/s eta 0:00:00
Downloading fastuuid-0.14.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (278 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.3/278.3 kB 31.6 MB/s eta 0:00:00
Downloading filelock-3.32.7-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.2/100.2 kB 12.7 MB/s eta 0:00:00
Downloading importlib_metadata-8.9.0-py3-none-any.whl (27 kB)
Downloading pydantic_settings-2.15.0-py3-none-any.whl (69 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 8.9 MB/s eta 0:00:00
Downloading botocore-1.43.108-py3-none-any.whl (16.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 135.3 MB/s eta 0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading s3transfer-0.19.2-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 kB 10.8 MB/s eta 0:00:00
Installing collected packages: typeguard, json-repair, jmespath, importlib-metadata, gepa, filelock, fastuuid, diskcache, botocore, asyncer, s3transfer, pydantic-settings, boto3, litellm, dspy
  Attempting uninstall: typeguard
    Found existing installation: typeguard 4.6.0
    Uninstalling typeguard-4.6.0:
      Successfully uninstalled typeguard-4.6.0
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib_metadata 9.0.1
    Uninstalling importlib_metadata-9.0.1:
      Successfully uninstalled importlib_metadata-9.0.1
  Attempting uninstall: filelock
    Found existing installation: filelock 4.0.7
    Uninstalling filelock-4.0.7:
      Successfully uninstalled filelock-4.0.7
Successfully installed asyncer-0.0.8 boto3-1.43.108 botocore-1.43.108 diskcache-5.6.3 dspy-3.2.1 fastuuid-0.14.0 filelock-3.32.7 gepa-0.0.27 importlib-metadata-8.9.0 jmespath-1.1.0 json-repair-0.63.5 litellm-1.104.0 pydantic-settings-2.15.0 s3transfer-0.19.2 typeguard-4.4.3

In [3]:
import pandas as pd
import dspy

# Data

In [4]:
optimisation_df = pd.read_excel('optimisation_set_articulation.xlsx')
validation_df = pd.read_excel('validation_set_articulation.xlsx')
test_df = pd.read_excel('test_set_articulation.xlsx')

In [5]:
optimisation_df

,context,current turn,Vishal's Codes,Jack's Codes,Agreed Codes,Notes
0,Dialogue context: MATT: All right. Vex? MARISH...,"LAURA: Oh, well, let's make this nice and easy...",act on game-state,act on game-state,act on game-state,NaN
1,Dialogue context: MARISHA: Just gnawing on the...,TRAVIS: (eager snarling),act on game-state,act on game-state,act on game-state,Maybe out of gameplay
2,"Dialogue context: LAURA: Oh, well, let's make ...","MATT: All right, Grog, it's your turn.",assert game-state,assert game-state,assert game-state,NaN
3,"Dialogue context: LAURA: Oh, well, let's make ...",TRAVIS: (eager snarling continues),act on game-state,act on game-state,act on game-state,Maybe out of gameplay
4,Dialogue context: TRAVIS: (eager snarling) MAT...,MARISHA: Does he get advantage because we're a...,question game-state,question game-state,question game-state,NaN
...,...,...,...,...,...,...
395,Dialogue context: TRAVIS: Yeah! (all laugh) MA...,ORION: That's a good idea. Grog! You can go hu...,out-of-gameplay,out-of-gameplay,out-of-gameplay,NaN
396,"Dialogue context: MATT: Oh, Grog. LAURA: That ...",LIAM: She can hump your leg.,out-of-gameplay,out-of-gameplay,out-of-gameplay,NaN
397,Dialogue context: LAURA: That would be the mos...,TRAVIS: Did you see her work in that room of b...,question game-state,out-of-gameplay,out-of-gameplay,NaN
398,Dialogue context: ORION: That's a good idea. G...,TALIESIN: Only one of them is demanding that I...,assert game-state,out-of-gameplay,out-of-gameplay,NaN
399,Dialogue context: LIAM: She can hump your leg....,MARISHA: Isn't Kima a dwarf?,question game-state,question game-state,question game-state,NaN

In [6]:
optimisation_df.drop(columns=['Jack\'s Codes'], inplace=True)

In [7]:
optimisation_df.drop(columns=['Vishal\'s Codes'], inplace=True)

In [8]:
optimisation_df.drop(columns=['Notes'], inplace=True)

In [9]:
validation_df.drop(columns=['Jack\'s Codes'], inplace=True)

In [10]:
validation_df.drop(columns=['Vishal\'s Codes'], inplace=True)

In [11]:
validation_df.drop(columns=['Notes'], inplace=True)

In [12]:
test_df.drop(columns=['Jack\'s Codes'], inplace=True)

In [13]:
test_df.drop(columns=['Vishal\'s Codes'], inplace=True)

In [14]:
test_df.drop(columns=['Notes'], inplace=True)

In [15]:
test_df

,context,current turn,Agreed Codes
0,Dialogue context: TRAVIS: So should we fly up ...,MARISHA: And we still have Pass Without a Trac...,propose intention or action
1,Dialogue context: TALIESIN: I think it'd be sa...,"LAURA: Yes, we do. She cast it.",acknowledge
2,Dialogue context: TRAVIS: Let's do it. MARISHA...,"MATT: All right, now that this brief combat ha...",NaN
3,Dialogue context: MARISHA: And we still have P...,"LAURA: You're like, ""Gladly!""",out-of-gameplay
4,"Dialogue context: MATT: All right, now that th...",LAURA: What about Pike? Because she just knelt...,argue
...,...,...,...
95,Dialogue context: TALIESIN: We all have to be ...,"LIAM: Yeah, that's right.",acknowledge
96,Dialogue context: TRAVIS: And he can fly. SAM:...,SAM: We have too many people for the carpet an...,argue
97,"Dialogue context: SAM: No, he can't. He's done...",LIAM: My wings are gone. There's no wings for ...,assert game-state
98,"Dialogue context: LIAM: Yeah, that's right. SA...","TRAVIS: Well, kick Trinket out of the necklace...",argue
99,Dialogue context: SAM: We have too many people...,"TALIESIN: I can also climb up the wall, if nee...",propose intention or action

In [16]:
optimisation_set = []

for context, question, response in optimisation_df.values:
    examples = dspy.Example(context=context, question=question, response=response).with_inputs("context", "question")
    optimisation_set.append(examples)

In [17]:
optimisation_set

[Example({'context': 'Dialogue context: MATT: All right. Vex? MARISHA: Just gnawing on the dead dwarf. MARISHA: Just gnawing on the dead dwarf.', 'question': 'LAURA: Oh, well, let\'s make this nice and easy. I smack Grog on the ass and say, "Go get him".', 'response': 'act on game-state'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: MARISHA: Just gnawing on the dead dwarf. LAURA: Oh, well, let\'s make this nice and easy. I smack Grog on the ass and say, "Go get him". LAURA: Oh, well, let\'s make this nice and easy. I smack Grog on the ass and say, "Go get him".', 'question': 'TRAVIS: (eager snarling)', 'response': 'act on game-state'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: LAURA: Oh, well, let\'s make this nice and easy. I smack Grog on the ass and say, "Go get him". LAURA: Oh, well, let\'s make this nice and easy. I smack Grog on the ass and say, "Go get him". TRAVIS: (eager snarling)', 'question': "MATT: All right, Grog, it's your turn.", 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: LAURA: Oh, well, let\'s make this nice and easy. I smack Grog on the ass and say, "Go get him". TRAVIS: (eager snarling) MATT: All right, Grog, it\'s your turn.', 'question': 'TRAVIS: (eager snarling continues)', 'response': 'act on game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: TRAVIS: (eager snarling) MATT: All right, Grog, it's your turn. TRAVIS: (eager snarling continues)", 'question': "MARISHA: Does he get advantage because we're all encouraging violence?", 'response': 'question game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MATT: All right, Grog, it's your turn. TRAVIS: (eager snarling continues) MARISHA: Does he get advantage because we're all encouraging violence?", 'question': 'ORION: Yeah, or inspiration?', 'response': 'question game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: TRAVIS: (eager snarling continues) MARISHA: Does he get advantage because we're all encouraging violence? ORION: Yeah, or inspiration?", 'question': 'MATT: Oh no, you get inspiration dice for this whole set up. 1d8 inspiration dice.', 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MARISHA: Does he get advantage because we're all encouraging violence? ORION: Yeah, or inspiration? MATT: Oh no, you get inspiration dice for this whole set up. 1d8 inspiration dice.", 'question': "SAM: You don't kill him in one shot, it's very very disappointing.", 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: ORION: Yeah, or inspiration? MATT: Oh no, you get inspiration dice for this whole set up. 1d8 inspiration dice. SAM: You don't kill him in one shot, it's very very disappointing.", 'question': 'MATT: All right, you run in.', 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MATT: Oh no, you get inspiration dice for this whole set up. 1d8 inspiration dice. SAM: You don't kill him in one shot, it's very very disappointing. MATT: All right, you run in.", 'question': 'TRAVIS: You said the room was full of shiny pointy things on the wall, right?', 'response': 'question game-state'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: MATT: All right, you run in. TRAVIS: You said the room was full of shiny pointy things on the wall, right? MATT: Yes.', 'question': 'TRAVIS: I would like to bull rush the dwarf up and against the wall, try and spear him with all the sharp shit on the wall.', 'response': 'propose intention or action'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: MATT: Yes. TRAVIS: I would like to bull rush the dwarf up and against the wall, try and spear him with all the sharp shit on the wall. MATT: Okay!', 'question': 'ALL: (cheering)', 'response': 'acknowledge'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: TRAVIS: I would like to bull rush the dwarf up and against the wall, try and spear him with all the sharp shit on the wall. MATT: Okay! ALL: (cheering)', 'question': "MATT: Oh, that's nasty. Okay then, so for the-- (laughs)", 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MATT: Okay! ALL: (cheering) MATT: Oh, that's nasty. Okay then, so for the-- (laughs)", 'question': "LIAM: Instant karma's going to get you, man.", 'response': 'out-of-gameplay'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: ALL: (cheering) MATT: Oh, that's nasty. Okay then, so for the-- (laughs) LIAM: Instant karma's going to get you, man.", 'question': 'MATT: All right, so go ahead and make an athletics check.', 'response': 'question game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MATT: Oh, that's nasty. Okay then, so for the-- (laughs) LIAM: Instant karma's going to get you, man. MATT: All right, so go ahead and make an athletics check.", 'question': 'LIAM: You hear that, Keyleth?', 'response': 'act on game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: LIAM: Instant karma's going to get you, man. MATT: All right, so go ahead and make an athletics check. LIAM: You hear that, Keyleth?", 'question': 'MARISHA: (growling)', 'response': 'act on game-state'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: MATT: All right, so go ahead and make an athletics check. LIAM: You hear that, Keyleth? MARISHA: (growling)', 'question': 'TRAVIS: 24.', 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: LIAM: You hear that, Keyleth? MARISHA: (growling) TRAVIS: 24.', 'question': "MATT: Yeah, against his 7. You rush in and with your first attack, you grab him, lift him, and you can see there's a series of giant meat hooks hanging from the back of the wall, and you just lift him up and (impaling SFX) shove him down onto the hook which protrudes from the front of his chest. (gurgling SFX)", 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MARISHA: (growling) TRAVIS: 24. MATT: Yeah, against his 7. You rush in and with your first attack, you grab him, lift him, and you can see there's a series of giant meat hooks hanging from the back of the wall, and you just lift him up and (impaling SFX) shove him down onto the hook which protrudes from the front of his chest. (gurgling SFX)", 'question': 'TRAVIS: No, perfect. Tell me I get another attack.', 'response': 'propose intention or action'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MATT: Yeah, against his 7. You rush in and with your first attack, you grab him, lift him, and you can see there's a series of giant meat hooks hanging from the back of the wall, and you just lift him up and (impaling SFX) shove him down onto the hook which protrudes from the front of his chest. (gurgling SFX) TRAVIS: No, perfect. Tell me I get another attack. MATT: You do.", 'question': 'TRAVIS: Excellent!', 'response': 'acknowledge'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: TRAVIS: No, perfect. Tell me I get another attack. MATT: You do. TRAVIS: Excellent!', 'question': "MATT: That's 12 points of damage and he's currently restrained by the hook through his chest.", 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MATT: You do. TRAVIS: Excellent! MATT: That's 12 points of damage and he's currently restrained by the hook through his chest.", 'question': 'LAURA: Impaled? Oh!', 'response': 'act on game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: TRAVIS: Excellent! MATT: That's 12 points of damage and he's currently restrained by the hook through his chest. LAURA: Impaled? Oh!", 'question': "TRAVIS: Perfect! With my second attack as he's screaming out I reach inside, grab his lower jaw and pull him straight down.", 'response': 'act on game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MATT: That's 12 points of damage and he's currently restrained by the hook through his chest. LAURA: Impaled? Oh! TRAVIS: Perfect! With my second attack as he's screaming out I reach inside, grab his lower jaw and pull him straight down.", 'question': 'MATT: Okay, make an attack roll.', 'response': 'question game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: LAURA: Impaled? Oh! TRAVIS: Perfect! With my second attack as he's screaming out I reach inside, grab his lower jaw and pull him straight down. MATT: Okay, make an attack roll.", 'question': "LAURA: Oh no! That's so gross.", 'response': 'out-of-gameplay'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: TRAVIS: Perfect! With my second attack as he's screaming out I reach inside, grab his lower jaw and pull him straight down. MATT: Okay, make an attack roll. LAURA: Oh no! That's so gross.", 'question': 'ASHLEY: Oh, I love this so much.', 'response': 'out-of-gameplay'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MATT: Okay, make an attack roll. LAURA: Oh no! That's so gross. ASHLEY: Oh, I love this so much.", 'question': 'LIAM: Vax is using his free hand to cover his eyes.', 'response': 'act on game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: LAURA: Oh no! That's so gross. ASHLEY: Oh, I love this so much. LIAM: Vax is using his free hand to cover his eyes.", 'question': 'SAM: Keyleth starts eating him.', 'response': 'out-of-gameplay'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: ASHLEY: Oh, I love this so much. LIAM: Vax is using his free hand to cover his eyes. SAM: Keyleth starts eating him.', 'question': 'TRAVIS: (laughing) 24.', 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: LIAM: Vax is using his free hand to cover his eyes. SAM: Keyleth starts eating him. TRAVIS: (laughing) 24.', 'question': 'MATT: (laughs) Go ahead and roll damage on this.', 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: SAM: Keyleth starts eating him. TRAVIS: (laughing) 24. MATT: (laughs) Go ahead and roll damage on this.', 'question': 'LAURA: Oh, sick.', 'response': 'acknowledge'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: TRAVIS: (laughing) 24. MATT: (laughs) Go ahead and roll damage on this. LAURA: Oh, sick.', 'question': 'TRAVIS: With a 12?', 'response': 'question game-state'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: MATT: (laughs) Go ahead and roll damage on this. LAURA: Oh, sick. TRAVIS: With a 12?', 'question': "MATT: For flavor, roll a 12. Why not? You're pulling his jaw.", 'response': 'question game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: LAURA: Oh, sick. TRAVIS: With a 12? MATT: For flavor, roll a 12. Why not? You're pulling his jaw.", 'question': 'TRAVIS: Excellent! (laughing)', 'response': 'acknowledge'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: TRAVIS: With a 12? MATT: For flavor, roll a 12. Why not? You're pulling his jaw. TRAVIS: Excellent! (laughing)", 'question': 'ASHLEY: He rolled really high.', 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: TRAVIS: Excellent! (laughing) ASHLEY: He rolled really high. TRAVIS: 15.', 'question': "MATT: After you throw him onto the hook, his axe clatters to the ground and he reaches up with his hands to grab you and it looks like he's pulling back to try and bring you in for a headbutt. This angry look of burning rage in his white eyes, this fucked-up duergar with all these scars on his face, as he reaches up towards you, you take your giant hand and jam it into his maw. With this horrible (choking SFX) sound, as you put all your muscle into it, glaring him in the face with a terrible grin you (breaking SFX) and yank the jaw off from the bottom of his head.", 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MATT: After you throw him onto the hook, his axe clatters to the ground and he reaches up with his hands to grab you and it looks like he's pulling back to try and bring you in for a headbutt. This angry look of burning rage in his white eyes, this fucked-up duergar with all these scars on his face, as he reaches up towards you, you take your giant hand and jam it into his maw. With this horrible (choking SFX) sound, as you put all your muscle into it, glaring him in the face with a terrible grin you (breaking SFX) and yank the jaw off from the bottom of his head. MATT: After you throw him onto the hook, his axe clatters to the ground and he reaches up with his hands to grab you and it looks like he's pulling back to try and bring you in for a headbutt. This angry look of burning rage in his white eyes, this fucked-up duergar with all these scars on his face, as he reaches up towards you, you take your giant hand and jam it into his maw. With this horrible (choking SFX) sound, as you put all your muscle into it, glaring him in the face with a terrible grin you (breaking SFX) and yank the jaw off from the bottom of his head. ALL: (cheering)", 'question': "MATT: A spatter of blood across the front of his mouth and his tongue dangling, he gives out this horrible (gagging scream) this gurgling scream as all the blood begins to pour up into his throat. With that, clutching the jaw with one hand, you begin to pummel him in the face over and over, with his jaw, as he's watching, his head slowly cave in.", 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MATT: After you throw him onto the hook, his axe clatters to the ground and he reaches up with his hands to grab you and it looks like he's pulling back to try and bring you in for a headbutt. This angry look of burning rage in his white eyes, this fucked-up duergar with all these scars on his face, as he reaches up towards you, you take your giant hand and jam it into his maw. With this horrible (choking SFX) sound, as you put all your muscle into it, glaring him in the face with a terrible grin you (breaking SFX) and yank the jaw off from the bottom of his head. ALL: (cheering) MATT: A spatter of blood across the front of his mouth and his tongue dangling, he gives out this horrible (gagging scream) this gurgling scream as all the blood begins to pour up into his throat. With that, clutching the jaw with one hand, you begin to pummel him in the face over and over, with his jaw, as he's watching, his head slowly cave in.", 'question': 'TRAVIS: (laughing) Yes!', 'response': 'acknowledge'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: ALL: (cheering) MATT: A spatter of blood across the front of his mouth and his tongue dangling, he gives out this horrible (gagging scream) this gurgling scream as all the blood begins to pour up into his throat. With that, clutching the jaw with one hand, you begin to pummel him in the face over and over, with his jaw, as he's watching, his head slowly cave in. TRAVIS: (laughing) Yes!", 'question': "SAM: I think he's going to make it.", 'response': 'out-of-gameplay'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MATT: A spatter of blood across the front of his mouth and his tongue dangling, he gives out this horrible (gagging scream) this gurgling scream as all the blood begins to pour up into his throat. With that, clutching the jaw with one hand, you begin to pummel him in the face over and over, with his jaw, as he's watching, his head slowly cave in. TRAVIS: (laughing) Yes! SAM: I think he's going to make it.", 'question': "MATT: Until eventually, he's no longer moving and you throw the jaw to the ground, just coated with blood.", 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: TRAVIS: (laughing) Yes! SAM: I think he's going to make it. MATT: Until eventually, he's no longer moving and you throw the jaw to the ground, just coated with blood.", 'question': "LIAM: You're going to pull through, buddy.", 'response': 'act on game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: SAM: I think he's going to make it. MATT: Until eventually, he's no longer moving and you throw the jaw to the ground, just coated with blood. LIAM: You're going to pull through, buddy.", 'question': 'LAURA: Pike! I think Grog, um, I think he did his job.', 'response': 'act on game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MATT: Until eventually, he's no longer moving and you throw the jaw to the ground, just coated with blood. LIAM: You're going to pull through, buddy. LAURA: Pike! I think Grog, um, I think he did his job.", 'question': 'ASHLEY: I scream out, "Good job Grog! That\'s your best one yet!"', 'response': 'act on game-state'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: LIAM: You\'re going to pull through, buddy. LAURA: Pike! I think Grog, um, I think he did his job. ASHLEY: I scream out, "Good job Grog! That\'s your best one yet!"', 'question': 'MARISHA: And they say video games are violent. (all laugh)', 'response': 'out-of-gameplay'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: LAURA: Pike! I think Grog, um, I think he did his job. ASHLEY: I scream out, "Good job Grog! That\'s your best one yet!" MARISHA: And they say video games are violent. (all laugh)', 'question': 'LAURA: (gagging sounds)', 'response': 'out-of-gameplay'}) (input_keys={'context', 'question'}),
 Example({'context': 'Dialogue context: ASHLEY: I scream out, "Good job Grog! That\'s your best one yet!" MARISHA: And they say video games are violent. (all laugh) LAURA: (gagging sounds)', 'question': "MATT: As you've entered the room now--", 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MARISHA: And they say video games are violent. (all laugh) LAURA: (gagging sounds) MATT: As you've entered the room now--", 'question': 'ASHLEY: Wait, is he dead? (all laugh)', 'response': 'question game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: LAURA: (gagging sounds) MATT: As you've entered the room now-- ASHLEY: Wait, is he dead? (all laugh)", 'question': "MATT: Oh, he's very dead.", 'response': 'assert game-state'}) (input_keys={'context', 'question'}),
 Example({'context': "Dialogue context: MATT: As you've entered the room now-- ASHLEY: Wait, is he dead? (all laugh) MATT: Oh, he's very dead.", 'question': 'TRAVIS: We made cheese of him.', 'response': 'assert game-state'}) (input_keys={'context', 'question'}),

# Language Model

In [40]:
lm = dspy.LM('ollama_chat/qwen3:4b', api_base = 'http://localhost:11434', api_key='', max_tokens=8192)
dspy.configure(lm=lm)

# Signatures

In [19]:
from typing import Literal

class TurnClassifier(dspy.Signature):
    """Given the context for a Dungeons & Dragons game turn and the game turn itself, classify the turn."""
    context: str = dspy.InputField(desc = "The three previous game turns which describe a player's action or their dialogue.")
    question: str = dspy.InputField (desc="The current turn taken by a player, which can include a description of an action or a piece of dialogue.")
    response: Literal['assert game-state',
                      'question game-state',
                      'act on game-state',
                      'propose intention or action',
                      'probe intention',
                      'acknowledge',
                      'argue',
                      'interact with resource',
                      ] = dspy.OutputField()

class PlayerInstruction(dspy.Signature):
  category: Literal['assert game-state',
                      'question game-state',
                      'act on game-state',
                      'propose intention or action',
                      'probe intention',
                      'acknowledge',
                      'argue',
                      'interact with resource',
                    ] = dspy.InputField()
  player_instruction:str = dspy.OutputField(desc="instruction on how to behave within a D&D game.")

# Modules

In [20]:
class ClassifyTurns(dspy.Module):
  def __init__(self):
    self.classifier = dspy.Predict(TurnClassifier, caching=False)

  def forward(self, context, question, **kwargs):
    prediction = self.classifier(context=context, question=question)
    return prediction

In [21]:
classify = ClassifyTurns()
def classify_turn(context, question):
    try:
        predicted_category = classify(context=context, question=question)
        return predicted_category
    except Exception as e:
        return 0

In [22]:
validation_set = []

for context, question, response in validation_df.values:
    examples = dspy.Example(context=context, question=question, response=response).with_inputs("context", "question")
    validation_set.append(examples)

In [23]:
test_df

,context,current turn,Agreed Codes
0,Dialogue context: TRAVIS: So should we fly up ...,MARISHA: And we still have Pass Without a Trac...,propose intention or action
1,Dialogue context: TALIESIN: I think it'd be sa...,"LAURA: Yes, we do. She cast it.",acknowledge
2,Dialogue context: TRAVIS: Let's do it. MARISHA...,"MATT: All right, now that this brief combat ha...",NaN
3,Dialogue context: MARISHA: And we still have P...,"LAURA: You're like, ""Gladly!""",out-of-gameplay
4,"Dialogue context: MATT: All right, now that th...",LAURA: What about Pike? Because she just knelt...,argue
...,...,...,...
95,Dialogue context: TALIESIN: We all have to be ...,"LIAM: Yeah, that's right.",acknowledge
96,Dialogue context: TRAVIS: And he can fly. SAM:...,SAM: We have too many people for the carpet an...,argue
97,"Dialogue context: SAM: No, he can't. He's done...",LIAM: My wings are gone. There's no wings for ...,assert game-state
98,"Dialogue context: LIAM: Yeah, that's right. SA...","TRAVIS: Well, kick Trinket out of the necklace...",argue
99,Dialogue context: SAM: We have too many people...,"TALIESIN: I can also climb up the wall, if nee...",propose intention or action

In [24]:
test_set = []

for context, question, response in test_df.values:
    examples = dspy.Example(context=context, question=question, response=response).with_inputs("context", "question")
    test_set.append(examples)

In [25]:
true_categories = []

for i in range(len(test_set)):
  true_categories.append(test_set[i]['response'])

In [26]:
true_categories

['propose intention or action',
 'acknowledge',
 nan,
 'out-of-gameplay',
 'argue',
 'argue',
 'out-of-gameplay',
 'assert game-state',
 'question game-state',
 'acknowledge',
 'out-of-gameplay',
 'out-of-gameplay',
 'out-of-gameplay',
 'assert game-state',
 'assert game-state',
 'assert game-state',
 'assert game-state',
 'question game-state',
 'question game-state',
 'question game-state',
 'interact with resource',
 'propose intention or action',
 'assert game-state',
 'acknowledge',
 'question game-state',
 'propose intention or action',
 'assert game-state',
 'assert game-state',
 'question game-state',
 'assert game-state',
 'assert game-state',
 'assert game-state',
 'question game-state',
 'assert game-state',
 'question game-state',
 'question game-state',
 'assert game-state',
 'question game-state',
 'question game-state',
 'assert game-state',
 'assert game-state',
 'question game-state',
 'propose intention or action',
 'question game-state',
 'assert game-state',
 'interact with resource',
 'assert game-state',
 'assert game-state',
 'assert game-state',
 'propose intention or action',
 'propose intention or action',
 'probe intention',
 'argue',
 'argue',
 'question game-state',
 'assert game-state',
 'propose intention or action',
 'acknowledge',
 'question game-state',
 'propose intention or action',
 'argue',
 'probe intention',
 'probe intention',
 'propose intention or action',
 'question game-state',
 'probe intention',
 'assert game-state',
 'probe intention',
 'argue',
 'assert game-state',
 'probe intention',
 'assert game-state',
 'argue',
 'argue',
 'assert game-state',
 'assert game-state',
 'assert game-state',
 'argue',
 'assert game-state',
 'argue',
 'acknowledge',
 'argue',
 'propose intention or action',
 'propose intention or action',
 'assert game-state',
 'interact with resource',
 'assert game-state',
 'question game-state',
 'interact with resource',
 'probe intention',
 'acknowledge',
 'assert game-state',
 'assert game-state',
 'assert game-state',
 'argue',
 'acknowledge',
 'argue',
 'assert game-state',
 'argue',
 'propose intention or action']

In [27]:
# unoptimised_predictions = []

# for i in range(len(validation_set)):
#     unoptimised_predictions.append(classify_turn(validation_set[i]['context'], validation_set[i]['question']))

In [28]:
# unoptimised_predicted_categories = []

# for i in range(len(unoptimised_predictions)):
#   unoptimised_predicted_categories.append(unoptimised_predictions[i].response)

In [29]:
# from sklearn.metrics import f1_score

# def f1(true_categories, predicted_categories, trace=None):
#   for i in range(len(true_categories)):
#     return f1_score(true_categories, predicted_categories, average='weighted')

In [30]:
# f1(true_categories, unoptimised_predicted_categories)

### Optimisation

In [31]:
# def normalize_label(label):
#     return dspy.Evaluate.evaluate.normalize_text


# def exact_match(true_categories, prediction, trace=None):
#     return prediction.response == true_categories

In [32]:
import math
from collections import Counter

def normalize_label(label):
    return " ".join(str(label).strip().lower().split())


# Calculate this from the TRAINING set only
class_counts = Counter(
    example.response
    for example in optimisation_set
)

# Square-root inverse-frequency weighting
class_weights = {
    label: 1.0 / math.sqrt(count)
    for label, count in class_counts.items()
}

# Normalize so the average class weight is 1
mean_weight = sum(class_weights.values()) / len(class_weights)

class_weights = {
    label: weight / mean_weight
    for label, weight in class_weights.items()
}


def class_balanced_reward(example, prediction, trace=None):
    expected = example.response
    predicted = prediction.response

    if predicted == expected:
        return class_weights[expected]

    return 0.0

In [33]:
optimisation_set[0]

Example({'context': 'Dialogue context: MATT: All right. Vex? MARISHA: Just gnawing on the dead dwarf. MARISHA: Just gnawing on the dead dwarf.', 'question': 'LAURA: Oh, well, let\'s make this nice and easy. I smack Grog on the ass and say, "Go get him".', 'response': 'act on game-state'}) (input_keys={'context', 'question'})

In [34]:
optimizer_copro = dspy.COPRO(metric=class_balanced_reward, breadth=3, depth=3, init_temperature=1.4, track_stats=True)
optimizer_fewshot = dspy.BootstrapFewShot(metric=class_balanced_reward, teacher_settings=None, max_bootstrapped_demos=8, max_labeled_demos=16)
optimizer_mipro = dspy.MIPROv2(metric=class_balanced_reward, auto=None, num_candidates=2)

In [35]:
!pip install dspy[optuna]==3.2.1

Requirement already satisfied: dspy==3.2.1 in /usr/local/lib/python3.13/dist-packages (from dspy[optuna]==3.2.1) (3.2.1)
Requirement already satisfied: openai>=0.28.1 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (2.54.0)
Requirement already satisfied: regex>=2023.10.3 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (2025.11.3)
Requirement already satisfied: orjson>=3.9.0 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (3.12.0)
Requirement already satisfied: tqdm>=4.66.1 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (4.67.3)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (2.32.4)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (2.13.5)
Requirement already satisfied: litellm>=1.64.0 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (1.104.0)
Requirement already satisfied: diskcache>=5.6.0 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (5.6.3)
Requirement already satisfied: json-repair>=0.54.2 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (0.63.5)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (9.1.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (4.15.1)
Requirement already satisfied: asyncer==0.0.8 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (0.0.8)
Requirement already satisfied: cachetools>=5.5.0 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (6.2.6)
Requirement already satisfied: cloudpickle>=3.1.2 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (3.1.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (2.1.3)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (4.0.1)
Requirement already satisfied: gepa==0.0.27 in /usr/local/lib/python3.13/dist-packages (from gepa[dspy]==0.0.27->dspy==3.2.1->dspy[optuna]==3.2.1) (0.0.27)
Requirement already satisfied: typeguard==4.4.3 in /usr/local/lib/python3.13/dist-packages (from dspy==3.2.1->dspy[optuna]==3.2.1) (4.4.3)
Collecting optuna>=3.4.0 (from dspy[optuna]==3.2.1)
  Downloading optuna-5.0.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: typing_extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from typeguard==4.4.3->dspy==3.2.1->dspy[optuna]==3.2.1) (4.16.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio->dspy==3.2.1->dspy[optuna]==3.2.1) (3.20)
Requirement already satisfied: fastuuid<1.0,>=0.14.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (0.14.0)
Requirement already satisfied: filelock<4.0,>=3.16.1 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (3.32.7)
Requirement already satisfied: httpx<1.0,>=0.28.0 in /usr/local/lib/python3.13/dist-packages (from httpx[http2]<1.0,>=0.28.0->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (0.28.1)
Requirement already satisfied: python-dotenv<2.0,>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (1.2.3)
Requirement already satisfied: pyyaml<7.0,>=6.0.3 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (6.0.3)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (26.3)
Requirement already satisfied: importlib-metadata<9.0,>=8.0.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (8.9.0)
Requirement already satisfied: tiktoken<1.0,>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (0.14.0)
Requirement already satisfied: tokenizers<1.0,>=0.21.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (0.23.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.34.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (1.33.0)
Requirement already satisfied: click<9.0,>=8.0.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (8.5.0)
Requirement already satisfied: jinja2<4.0,>=3.1.6 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (3.1.6)
Requirement already satisfied: aiohttp<4.0,>=3.14.2 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (3.14.3)
Requirement already satisfied: pydantic-settings<3.0,>=2.14.1 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (2.15.0)
Requirement already satisfied: jsonschema<5.0,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (4.26.0)
Requirement already satisfied: boto3<2.0,>=1.43.1 in /usr/local/lib/python3.13/dist-packages (from litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (1.43.108)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from openai>=0.28.1->dspy==3.2.1->dspy[optuna]==3.2.1) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.13/dist-packages (from openai>=0.28.1->dspy==3.2.1->dspy[optuna]==3.2.1) (0.17.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.13/dist-packages (from openai>=0.28.1->dspy==3.2.1->dspy[optuna]==3.2.1) (1.3.1)
Collecting alembic>=1.5.0 (from optuna>=3.4.0->dspy[optuna]==3.2.1)
  Downloading alembic-1.20.0-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna>=3.4.0->dspy[optuna]==3.2.1)
  Downloading colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from optuna>=3.4.0->dspy[optuna]==3.2.1) (2.1.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.0->dspy==3.2.1->dspy[optuna]==3.2.1) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.0->dspy==3.2.1->dspy[optuna]==3.2.1) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.0->dspy==3.2.1->dspy[optuna]==3.2.1) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31.0->dspy==3.2.1->dspy[optuna]==3.2.1) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31.0->dspy==3.2.1->dspy[optuna]==3.2.1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31.0->dspy==3.2.1->dspy[optuna]==3.2.1) (2026.7.22)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0,>=3.14.2->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0,>=3.14.2->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0,>=3.14.2->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0,>=3.14.2->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0,>=3.14.2->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0,>=3.14.2->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4.0,>=3.14.2->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (1.25.1)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna>=3.4.0->dspy[optuna]==3.2.1) (1.3.2.dev0)
Requirement already satisfied: botocore<1.44.0,>=1.43.108 in /usr/local/lib/python3.13/dist-packages (from boto3<2.0,>=1.43.1->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (1.43.108)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.13/dist-packages (from boto3<2.0,>=1.43.1->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (1.1.0)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in /usr/local/lib/python3.13/dist-packages (from boto3<2.0,>=1.43.1->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (0.19.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0,>=0.28.0->httpx[http2]<1.0,>=0.28.0->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0,>=0.28.0->httpx[http2]<1.0,>=0.28.0->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (0.16.0)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.13/dist-packages (from httpx[http2]<1.0,>=0.28.0->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (4.4.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.34.0->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.34.0->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (1.6.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.13/dist-packages (from importlib-metadata<9.0,>=8.0.0->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (4.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2<4.0,>=3.1.6->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (3.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema<5.0,>=4.0.0->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema<5.0,>=4.0.0->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema<5.0,>=4.0.0->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (2026.6.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.13/dist-packages (from botocore<1.44.0,>=1.43.108->boto3<2.0,>=1.43.1->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (2.9.0.post0)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.13/dist-packages (from h2<5,>=3->httpx[http2]<1.0,>=0.28.0->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (6.1.0)
Requirement already satisfied: hpack<5,>=4.2 in /usr/local/lib/python3.13/dist-packages (from h2<5,>=3->httpx[http2]<1.0,>=0.28.0->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (4.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.44.0,>=1.43.108->boto3<2.0,>=1.43.1->litellm>=1.64.0->dspy==3.2.1->dspy[optuna]==3.2.1) (1.17.0)
Downloading optuna-5.0.0-py3-none-any.whl (442 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.4/442.4 kB 807.1 kB/s eta 0:00:00
Downloading alembic-1.20.0-py3-none-any.whl (268 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.7/268.7 kB 5.0 MB/s eta 0:00:00
Downloading colorlog-6.12.0-py3-none-any.whl (12 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.20.0 colorlog-6.12.0 optuna-5.0.0

In [36]:
import litellm

In [37]:
litellm.drop_params=True

In [41]:
fewshot_classifier = optimizer_fewshot.compile(classify, trainset=optimisation_set)

  1%|▏         | 5/400 [00:45<1:00:04,  9.13s/it]

Bootstrapped 4 full traces after 5 examples for up to 1 rounds, amounting to 5 attempts.

In [42]:
fewshot_classifier.save("fewshot_classifier.json")

In [43]:
classify.load("fewshot_classifier.json")

Evaluation

In [44]:
# evaluate = dspy.Evaluate(devset=validation_set, metric = semanticF1, num_threads=1, provide_traceback=True)

In [45]:
# evaluate(fewshot_classifier)

In [46]:
predictions = []

for i in range(len(test_set)):
    predictions.append(classify(test_set[i]['context'], test_set[i]['question']))

In [47]:
predicted_categories = []

for i in range(len(predictions)):
  predicted_categories.append(predictions[i].response)

In [48]:
true_categories = []

for i in range(len(test_set)):
  true_categories.append(test_set[i]['response'])

In [49]:
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    classification_report,
    confusion_matrix,
)


def evaluate_classifier(classifier, dataset):

    y_true = true_categories
    y_pred = predicted_categories

    return {
        "accuracy": accuracy_score(y_true, y_pred),
        "macro_f1": f1_score(
            y_true, y_pred,
            average="macro",
            zero_division=0
        ),
        "weighted_f1": f1_score(
            y_true, y_pred,
            average="weighted",
            zero_division=0
        ),
        "macro_precision": precision_score(
            y_true, y_pred,
            average="macro",
            zero_division=0
        ),
        "macro_recall": recall_score(
            y_true, y_pred,
            average="macro",
            zero_division=0
        ),
    }

In [50]:
evaluate_classifier(classify, test_set)

{'accuracy': 0.45,
 'macro_f1': 0.28670986122599024,
 'weighted_f1': 0.4862244279018473,
 'macro_precision': 0.30099206349206353,
 'macro_recall': 0.2865291571173924}